spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:h2:mem:cho;NON_KEYWORDS=USER
    usernama: sa
    password:
    driver-class-name: org.h2.Driver

cho:
  hello:
    - "1"
    - "2"
    - "3"
  mapTest:
    name: "hey"
    resp: "success"
  KEY: "GNestrg5aea6Wyt+k31NyjOrpszmlVsnVOjwQ3wZNjs="
