spring:
  h2:
    console:
      enabled: true
      path: /hr-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:cho
    usernama: sa
    password:
    driver-class-name: org.h2.Driver
