spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      model: always

  datasource:
    url: jdbc:h2:mem:cho
    usernama: sa
    password:
    driver-class-name: org.h2.Driver
